### ISSUE TITLE
Error while scanning Cisco C1000 Switch

### ISSUE THREAD

**Issue by unionym** [RUB-NDS/Terrapin-Scanner#4]
**Error Case1:**
Terrapin_Scanner_Windows_amd64.exe -connect 192.168.123.2
panic: error while reading packet length of binary packet: EOF

goroutine 1 [running]:
main.main()
        /home/fabian/GolandProjects/Terrapin-Scanner/main.go:317 +0x1c7

**Error Case2:**
Terrapin_Scanner_Windows_amd64.exe -listen 192.168.123.2
panic: listen tcp: lookup tcp/192.168.123.2: getaddrinfow: The specified class was not found.

goroutine 1 [running]:
main.main()
        /home/fabian/GolandProjects/Terrapin-Scanner/main.go:323 +0x1b6

**Error Case3:**
Terrapin_Scanner_Windows_amd64.exe -listen 192.168.123.2:22
panic: listen tcp 192.168.123.2:22: bind: The requested address is not valid in its context.

goroutine 1 [running]:
main.main()
        /home/fabian/GolandProjects/Terrapin-Scanner/main.go:323 +0x1b6

**Error Case4:**
Terrapin_Scanner_Windows_amd64.exe -connect 192.168.123.2:22
panic: error while reading packet length of binary packet: EOF

goroutine 1 [running]:
main.main()
        /home/fabian/GolandProjects/Terrapin-Scanner/main.go:317 +0x1c7

**Comment by TrueSkrillor** [comment]
Thanks for the report. Can you please confirm that error cases 1 and 4 persist with the recently released version 1.0.3? This seems to be similar to #1. Error cases 2 and 3 indicate that you are trying to use `-listen` (which is meant for scanning clients) with a remote IP address. Given the case that you are trying to scan a server, the commands in 1 and 4 are correct.
